desc: Test runner for canwork-cli. Leave the commented examples so when you develop a sub command you have an example to work with
triggers:
- name: ""
  pattens:
  - '**/*.go'
  - '**/*.yml'
  env:
    DEBUG: "1"
  # cmd: go build && ./canwork-cli login --keyFile ~/tooling/keys/canwork/can-work-cam-firebase.json --email cam.asoftware@gmail.com --verbose
  cmd: go build -o canwork-cli && ./canwork-cli jobs --jobID="a584fa26-2647-6e5a-8871-a6ab89974f05" --keyFile ~/tooling/keys/canwork/can-work-production.json
  # cmd: go build && ./canwork-cli login
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: ""
watch_paths:
- .
watch_depth: 0
